# Generated by Django 4.2.30 on 2026-05-14 14:34

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_add_style_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='main_background_color',
            field=models.CharField(default='#f5f7fa', max_length=7, validators=[config.models.validate_hex_color]),
        ),
    ]
