# Generated by Django 4.2.30 on 2026-05-08 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Melody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('notation', models.TextField()),
                ('key', models.CharField(default='C', max_length=3)),
                ('share_id', models.CharField(db_index=True, max_length=12, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_count', models.IntegerField(editable=False)),
                ('duration_seconds', models.FloatField(editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melodies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'melodies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='melodies_user_id_85e483_idx')],
            },
        ),
    ]
