# Generated by Django 4.2.30 on 2026-05-11 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('melodies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelodyTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(choices=[('piano', 'Piano in C'), ('saxophone', 'Saxophone in Eb'), ('trumpet', 'Trumpet in Bb'), ('trombone', 'Trombone in C')], max_length=20)),
                ('notation', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('melody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='melodies.melody')),
            ],
            options={
                'db_table': 'melody_tabs',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['melody', 'position'], name='melody_tabs_melody__bbfc8f_idx'), models.Index(fields=['melody', 'instrument'], name='melody_tabs_melody__795c34_idx')],
            },
        ),
    ]
