# Generated by Django 4.2.30 on 2026-05-11 16:11

import uuid
from django.db import migrations


def create_default_tabs(apps, schema_editor):
    Melody = apps.get_model('melodies', 'Melody')
    MelodyTab = apps.get_model('melodies', 'MelodyTab')

    for melody in Melody.objects.filter(notation__isnull=False).exclude(notation=''):
        if not MelodyTab.objects.filter(melody=melody).exists():
            MelodyTab.objects.create(
                id=uuid.uuid4(),
                melody=melody,
                instrument='piano',
                notation=melody.notation,
                position=0,
            )


def remove_default_tabs(apps, schema_editor):
    MelodyTab = apps.get_model('melodies', 'MelodyTab')
    MelodyTab.objects.filter(instrument='piano', position=0, suffix__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('melodies', '0002_melodytab'),
    ]

    operations = [
        migrations.RunPython(create_default_tabs, remove_default_tabs),
    ]
