# Generated by Django 4.2.30 on 2026-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodies', '0003_add_default_piano_tabs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='melody',
            index=models.Index(fields=['is_public', '-created_at'], name='melodies_is_publ_a5d790_idx'),
        ),
    ]
