# Generated by Django 4.2.30 on 2026-05-09 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('melodies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('share_id', models.CharField(db_index=True, max_length=12, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('melody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist_entries', to='melodies.melody')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='setlists.setlist')),
            ],
            options={
                'db_table': 'setlist_entries',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['setlist', 'position'], name='setlist_ent_setlist_f75803_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(fields=['user', '-created_at'], name='setlists_user_id_229664_idx'),
        ),
    ]
