# Generated by Django 4.2.30 on 2026-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
